/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GrimoireRouteImport } from './routes/grimoire'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionMissionIdRouteImport } from './routes/mission.$missionId'

const GrimoireRoute = GrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMissionIdRoute = MissionMissionIdRouteImport.update({
  id: '/mission/$missionId',
  path: '/mission/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/grimoire': typeof GrimoireRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/grimoire': typeof GrimoireRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/grimoire': typeof GrimoireRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases' | '/grimoire' | '/mission/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases' | '/grimoire' | '/mission/$missionId'
  id: '__root__' | '/' | '/cases' | '/grimoire' | '/mission/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  GrimoireRoute: typeof GrimoireRoute
  MissionMissionIdRoute: typeof MissionMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/grimoire': {
      id: '/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof GrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$missionId': {
      id: '/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof MissionMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  GrimoireRoute: GrimoireRoute,
  MissionMissionIdRoute: MissionMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
